export enum EventsRegistry {
  REQUEST_PHONES = 'REQUEST_PHONES',
  RESPONSE_PHONES = 'RESPONSE_PHONES',
  REQUEST_PHONE = 'REQUEST_PHONE',
  PHONE_SELECTED_FOR_DISPLAY = 'PHONE_SELECTED_FOR_DISPLAY',
  PHONE_SELECTED_FOR_BUYING = 'PHONE_SELECTED_FOR_BUYING',
  RESPONSE_PHONE = 'RESPONSE_PHONE',
  GO_TO_SHOPPINGCART = 'GO_TO_SHOPPINGCART',
  GO_TO_SEARCH_PHONES = 'GO_TO_SEARCH_PHONES',
}